Vagrant.configure("2") do |config|
    config.vm.define "cpl" do |cpl|
      cpl.vm.provider "virtualbox" do |vb_cpl|
        vb_cpl.memory = 2048
        vb_cpl.cpus = 2
      end
      cpl.vm.box = "generic/ubuntu2004"
      cpl.vm.hostname = "k8s-cpl-1"
      cpl.vm.network "private_network", ip: "192.168.33.10"
    end
    config.vm.define "wrk" do |wrk|
      wrk.vm.provider "virtualbox" do |vb_wrk|
          vb_wrk.memory = 2048
          vb_wrk.cpus = 2
        end
      wrk.vm.box = "generic/ubuntu2004"
      wrk.vm.hostname = "k8s-wrk-1"
      wrk.vm.network "private_network", ip: "192.168.33.11"
    end
    config.vm.provision "file", source: "~/.ssh", destination: "~/ssh"
    config.vm.provision "shell", path: "provision.sh", privileged: true
end